//go:build !non_deploy

/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package subctl

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/AlecAivazis/survey/v2"
	"github.com/spf13/cobra"
	"github.com/submariner-io/admiral/pkg/reporter"
	"github.com/submariner-io/admiral/pkg/slices"
	"github.com/submariner-io/subctl/internal/constants"
	"github.com/submariner-io/subctl/internal/exit"
	"github.com/submariner-io/subctl/internal/nodes"
	"github.com/submariner-io/subctl/internal/restconfig"
	"github.com/submariner-io/subctl/pkg/broker"
	"github.com/submariner-io/subctl/pkg/client"
	"github.com/submariner-io/subctl/pkg/cluster"
	"github.com/submariner-io/subctl/pkg/join"
	"github.com/submariner-io/submariner-operator/pkg/discovery/network"
	"k8s.io/client-go/kubernetes"
)

type JoinCommand struct {
	cmd                *cobra.Command
	flags              join.Options
	labelGateway       bool
	restConfigProducer *restconfig.Producer
}

var JoinClusterToBroker = join.ClusterToBroker

func init() {
	rootCmd.AddCommand(NewJoinCmd())
}

func NewJoinCmd() *cobra.Command {
	joinCmd := &JoinCommand{
		cmd:                nil,
		restConfigProducer: restconfig.NewProducer(),
	}

	joinCmd.cmd = &cobra.Command{
		Use:   "join",
		Short: "Connect a cluster to an existing broker",
		Args: func(cmd *cobra.Command, args []string) error {
			return joinCmd.checkArguments(args)
		},
		Run: func(_ *cobra.Command, args []string) {
			status := NewReporter()

			brokerInfo, err := broker.ReadInfoFromFile(args[0])
			exit.OnError(status.Error(err, "Error loading the broker information from the given file"))
			status.Success("%s indicates broker is at %s", args[0], brokerInfo.BrokerURL)

			if joinCmd.flags.BrokerURL != "" {
				status.Success("Overriding broker URL using %s", joinCmd.flags.BrokerURL)
				brokerInfo.BrokerURL = joinCmd.flags.BrokerURL
			}

			exit.OnError(joinCmd.restConfigProducer.RunOnSelectedContext(
				func(clusterInfo *cluster.Info, _ string, status reporter.Interface) error {
					return joinCmd.joinInContext(brokerInfo, clusterInfo, status)
				}, status))
		},
	}

	joinCmd.addFlags()
	joinCmd.restConfigProducer.SetupFlags(joinCmd.cmd.Flags())

	return joinCmd.cmd
}

func (c *JoinCommand) checkArguments(args []string) error {
	if len(args) == 0 {
		return errors.New("the broker-info.subm file argument generated by 'subctl deploy-broker' is missing")
	}

	err := cobra.MaximumNArgs(1)(c.cmd, args)
	if err != nil {
		return err
	}

	return checkImageOverrides(c.flags.ImageOverrideArr)
}

func addLoadBalancerFlag(cmd *cobra.Command, p *bool) {
	cmd.Flags().BoolVar(p, "load-balancer", false, "enable automatic LoadBalancer in front of the gateways")
}

func addAirGappedFlag(cmd *cobra.Command, p *bool) {
	cmd.Flags().BoolVar(p, "air-gapped", false, "specifies that the cluster is in an air-gapped environment")
}

func (c *JoinCommand) addFlags() {
	c.cmd.Flags().StringVar(&c.flags.ClusterID, "clusterid", "", "cluster ID used to identify the tunnels")
	c.cmd.Flags().StringVar(&c.flags.ServiceCIDR, "servicecidr", "", "comma-separated service CIDRs")
	c.cmd.Flags().StringVar(&c.flags.ClusterCIDR, "clustercidr", "", "comma-separated cluster CIDRs")
	c.cmd.Flags().StringVar(&c.flags.Repository, "repository", "", "image repository")
	c.cmd.Flags().StringVar(&c.flags.ImageVersion, "version", "", "image version")
	c.cmd.Flags().IntVar(&c.flags.NATTPort, "nattport", 4500, "IPsec NATT port")
	c.cmd.Flags().BoolVar(&c.flags.NATTraversal, "natt", true, "enable NAT traversal for IPsec")
	c.cmd.Flags().BoolVar(&c.flags.PreferredServer, "preferred-server", false,
		"enable this cluster as a preferred server for dataplane connections")

	addAirGappedFlag(c.cmd, &c.flags.AirGappedDeployment)
	addLoadBalancerFlag(c.cmd, &c.flags.LoadBalancerEnabled)
	addImageOverrideFlag(c.cmd.Flags(), &c.flags.ImageOverrideArr)
	addHTTPProxyFlags(c.cmd.Flags(), &c.flags.HTTPProxyConfig)

	c.cmd.Flags().BoolVar(&c.flags.ForceUDPEncaps, "force-udp-encaps", false, "force UDP encapsulation for IPSec")

	c.cmd.Flags().BoolVar(&c.flags.IPSecDebug, "ipsec-debug", false, "enable IPsec debugging (verbose logging)")
	c.cmd.Flags().BoolVar(&c.flags.SubmarinerDebug, "pod-debug", false,
		"enable Submariner pod debugging (verbose logging in the deployed pods)")
	c.cmd.Flags().BoolVar(&c.flags.OperatorDebug, "operator-debug", false, "enable operator debugging (verbose logging)")
	c.cmd.Flags().BoolVar(&c.labelGateway, "label-gateway", true, "label gateways if necessary")
	c.cmd.Flags().StringVar(&c.flags.CableDriver, "cable-driver", "libreswan", "cable driver implementation")
	c.cmd.Flags().UintVar(&c.flags.GlobalnetClusterSize, "globalnet-cluster-size", 0,
		"cluster size for GlobalCIDR allocated to this cluster (amount of global IPs)")
	c.cmd.Flags().StringVar(&c.flags.GlobalnetCIDR, "globalnet-cidr", "",
		"GlobalCIDR to be allocated to the cluster")
	c.cmd.Flags().StringSliceVar(&c.flags.CustomDomains, "custom-domains", nil,
		"list of domains to use for multicluster service discovery")
	c.cmd.Flags().BoolVar(&c.flags.HealthCheckEnabled, "health-check", true,
		"enable Gateway health check")
	c.cmd.Flags().UintVar(&c.flags.HealthCheckInterval, "health-check-interval", 1,
		"interval in seconds between health check packets")
	c.cmd.Flags().UintVar(&c.flags.HealthCheckMaxPacketLossCount, "health-check-max-packet-loss-count", 5,
		"maximum number of packets lost before the connection is marked as down")
	c.cmd.Flags().BoolVar(&c.flags.GlobalnetEnabled, "globalnet", true,
		"enable/disable Globalnet for this cluster")
	c.cmd.Flags().StringVar(&c.flags.CoreDNSCustomConfigMap, "coredns-custom-configmap", "",
		"Name of the custom CoreDNS configmap to configure forwarding to lighthouse. It should be in "+
			"<namespace>/<name> format where <namespace> is optional and defaults to kube-system")
	c.cmd.Flags().BoolVar(&c.flags.IgnoreRequirements, "ignore-requirements", false, "ignore requirement failures (unsupported)")

	c.cmd.Flags().BoolVar(&c.flags.BrokerK8sSecure, "check-broker-certificate", true,
		"check the broker certificate (disable this to allow \"insecure\" connections)")
	c.cmd.Flags().StringVar(&c.flags.BrokerURL, "broker-url", "",
		"URL of the broker API endpoint (overrides the URL stored in the broker information file)")
	c.cmd.Flags().BoolVar(&c.flags.EnableClustersetIP, "enable-clusterset-ip", false,
		"set default support for use of clusterset IP for exported services in the cluster (default disabled)")
	c.cmd.Flags().StringVar(&c.flags.ClustersetIPCIDR, "clusterset-ip-cidr", "",
		"Clusterset IP CIDR to be allocated to the cluster")
	c.cmd.Flags().BoolVar(&c.flags.DisableIntraClusterConnectivity, "disable-intra-cluster-connectivity", false,
		"disable intra-cluster connectivity in the Route Agent. Only inter-cluster connectivity is performed")
	c.cmd.Flags().BoolVar(
		&c.flags.UseIPSecCertAuthMode,
		"use-ipsec-cert-auth-mode",
		false,
		"Use certificates for authentication when OVN IPsec is enabled",
	)
}

func (c *JoinCommand) joinInContext(brokerInfo *broker.Info, clusterInfo *cluster.Info, status reporter.Interface) error {
	c.determineClusterID(clusterInfo.Name, status)

	ctx := context.TODO()
	networkDetails := getNetworkDetails(ctx, clusterInfo.ClientProducer, status)
	c.flags.ClusterCIDR = determineCIDR("Pod", c.flags.ClusterCIDR, networkDetails.PodCIDRs, status)
	c.flags.ServiceCIDR = determineCIDR("Service", c.flags.ServiceCIDR, networkDetails.ServiceCIDRs, status)

	if brokerInfo.IsConnectivityEnabled() && c.labelGateway {
		possiblyLabelGateway(clusterInfo.ClientProducer.ForKubernetes(), status)
	}

	if c.flags.CustomDomains == nil && brokerInfo.CustomDomains != nil {
		c.flags.CustomDomains = *brokerInfo.CustomDomains
	}

	return JoinClusterToBroker(ctx, brokerInfo, &c.flags, clusterInfo.ClientProducer, status)
}

func possiblyLabelGateway(kubeClient kubernetes.Interface, status reporter.Interface) {
	status.Start("Retrieving the gateway nodes")
	defer status.End()

	gatewayNodes, err := nodes.ListGateways(kubeClient)
	exit.OnError(status.Error(err, "Error retrieving the gateway nodes"))

	if len(gatewayNodes) > 0 {
		fmt.Printf("   There are %d node(s) labeled as gateways:\n", len(gatewayNodes))

		for i := range gatewayNodes {
			fmt.Printf("    - %s\n", gatewayNodes[i])
		}

		return
	}

	// No Gateway nodes are present, get all worker nodes and ask user to select one of them as gateway node
	status.Start("Retrieving all worker nodes")

	workerNodes, err := nodes.GetAllWorkerNames(kubeClient)
	exit.OnError(status.Error(err, "Error listing the worker nodes"))

	status.End()

	if len(workerNodes) == 0 {
		status.Warning("No worker node available to label as the gateway")
		return
	}

	var nodeToLabel string
	if len(workerNodes) == 1 {
		nodeToLabel = workerNodes[0]
	} else {
		nodeToLabel, err = askForGatewayNode(workerNodes)
		exit.OnError(status.Error(err, "Error getting gateway node"))
	}

	status.Start("Labeling node %q as a gateway", nodeToLabel)

	err = nodes.LabelAsGateway(kubeClient, nodeToLabel)
	exit.OnError(status.Error(err, "Error labeling node %q as a gateway", nodeToLabel))
}

func askForGatewayNode(workerNodeNames []string) (string, error) {
	qs := []*survey.Question{
		{
			Name: "node",
			Prompt: NewInputPrompt(&survey.Select{
				Message: "Which node should be used as the gateway?",
				Options: workerNodeNames,
			}),
		},
	}

	answers := struct {
		Node string
	}{}

	err := survey.Ask(qs, &answers)

	return answers.Node, err //nolint:wrapcheck // No need to wrap here
}

func askForClusterID() (string, error) {
	// Missing information
	qs := []*survey.Question{}

	qs = append(qs, &survey.Question{
		Name:   "clusterID",
		Prompt: NewInputPrompt(&survey.Input{Message: "What is your cluster ID?"}),
		Validate: func(val interface{}) error {
			str, ok := val.(string)
			if !ok {
				return nil
			}

			return cluster.IsValidID(str)
		},
	})

	answers := struct {
		ClusterID string
	}{}

	err := survey.Ask(qs, &answers)

	return answers.ClusterID, err //nolint:wrapcheck // No need to wrap here
}

func askForCIDR(name string) (string, error) {
	qs := []*survey.Question{{
		Name: "cidr",
		Prompt: NewInputPrompt(&survey.Input{Message: fmt.Sprintf(
			"What's the %s CIDR for your cluster (comma-separated for multiple)?", name)}),
		Validate: survey.Required,
	}}

	answers := struct {
		Cidr string
	}{}

	err := survey.Ask(qs, &answers)

	return strings.TrimSpace(answers.Cidr), err
}

func (c *JoinCommand) determineClusterID(clusterName string, status reporter.Interface) {
	var err error

	if c.flags.ClusterID == "" {
		c.flags.ClusterID = clusterName

		if err = cluster.IsValidID(c.flags.ClusterID); err != nil {
			c.flags.ClusterID = cluster.SanitizeID(c.flags.ClusterID)
		}
	}

	if c.flags.ClusterID != "" {
		err = cluster.IsValidID(c.flags.ClusterID)
		if err != nil {
			_ = status.Error(err, "Invalid cluster ID")
			c.flags.ClusterID = ""
		}
	}

	if c.flags.ClusterID == "" {
		c.flags.ClusterID, err = askForClusterID()
		exit.OnError(status.Error(err, "Error collecting cluster ID"))
	}
}

func getNetworkDetails(ctx context.Context, clientProducer client.Producer, status reporter.Interface) *network.ClusterNetwork {
	status.Start("Discovering network details")

	networkDetails, err := network.Discover(ctx, clientProducer.ForGeneral(), constants.OperatorNamespace)
	if err != nil {
		status.Warning("Unable to discover network details: %s", err)
	} else if networkDetails == nil {
		status.Warning("No network details discovered")
	}

	status.End()

	if networkDetails != nil {
		networkDetails.Show()
	} else {
		networkDetails = &network.ClusterNetwork{}
	}

	return networkDetails
}

func determineCIDR(name, reqCIDR string, detectedCIDRs []string, status reporter.Interface) string {
	if reqCIDR != "" {
		reqCIDRs := strings.Split(reqCIDR, ",")
		if len(detectedCIDRs) > 0 && !slices.Equivalent(detectedCIDRs, reqCIDRs, slices.Key[string]) {
			status.Warning("The provided %s CIDR for the cluster (%s) does not match the discovered CIDR (%s)",
				name, reqCIDR, strings.Join(detectedCIDRs, ","))
		}
	} else if len(detectedCIDRs) == 0 {
		var err error
		reqCIDR, err = askForCIDR(name)
		exit.OnError(status.Error(err, "Error collecting CIDR"))
	}

	return reqCIDR
}
