---
name: Cross-Build Checks

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, converted_to_draft, labeled]

permissions: {}

jobs:
  cross:
    name: Cross-Build
    if: |
      (github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test-draft'))
      && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Build all supported binaries
        run: make build-cross
