---
name: subctl

on:
  pull_request:

jobs:
  test-subctl:
    name: subctl kubeconfig commands
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Check that all subctl commands work
        run: make test-subctl

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@release-0.13
